### ISSUE TITLE
2D array for sum optimization

### ISSUE THREAD

**Issue by erickingxu** [mateuszbuda/GPUExample#1]
Hi @mateuszbuda ,
Thanks for your great work. I am MetalImage author, and I using metal to do some gpu to process images and videos with meeting a problem for calculate the frame average.
So i try to transfer your shader to 2d (image size : 512*512 ), so I need add a for loop to calculate every line data. But it is slow. Can you had implemented a 2d shader for this ?
Thanks from ek

**Comment by mateuszbuda** [comment]
Can you be more specific?
Do you have any working code somewhere that you want to optimize?

**Comment by erickingxu** [comment]
Hi @mateuszbuda ，
thanks for your reply.
codes:

let   encoderInstNorm0 = commandBuffer.makeComputeCommandEncoder()
        encoderInstNorm0.setComputePipelineState(pipelineInstanceNorm)//for sum shader
        encoderInstNorm0.setTexture(mpsImage.texture, at: 0)//mpsImage is a MPSImage with 512*512 and featureChannels is 16
        encoderInstNorm0.setBuffer(sumBuffer, offset: 0, at: 0)//is a reslut buffer for restoring int value,length is 1

and shader should be like this:
kernel void reduce4(texture2d_array<float, access::read> inTexture[[texture(0)]],
                              volatile device atomic_int *result [[ buffer(1) ]],
                              uint3 id [[ thread_position_in_grid ]],
                              uint3 tid [[ thread_index_in_threadgroup ]],
                              uint3 bid [[ threadgroup_position_in_grid ]],
                              uint3 blockDim [[ threads_per_threadgroup ]]) {
///how to do?
}

Thanks

**Comment by mateuszbuda** [comment]
OK @erickingxu. I can try to answer your "how to do?", but my question is "what to do?".

**Comment by erickingxu** [comment]
HI @mateuszbuda ,
Thanks. And I need to calculate sum of inTexture pixels ( in every MPSImage's featureChannel ) with GPU in Metal.
MPSImage  ----->  vec4(sumR, sumG, sumB, nfeatureChannel)

**Comment by erickingxu** [comment]
Hi @mateuszbuda ,
maybe you can try a 2d texture for calculate sum of rgb value at first.

**Comment by erickingxu** [comment]
Hi @mateuszbuda ,
I try to write a 2d texture sum calculation as follows, if you had some time to check it ,I will be very appreciated and thanks. And then some time cost for loop y ,can you give me some advice?
/* halved number of blocks */
#define THREADGROUP_SIZE  16
kernel void sumReduceOptimize1(texture2d<float, access::read> inTexture[[texture(0)]],
                              volatile device atomic_int *result [[ buffer(1) ]],
                              uint2 id [[ thread_position_in_grid ]],
                              uint2 tid [[ thread_index_in_threadgroup ]],
                              uint2 bid [[ threadgroup_position_in_grid ]],
                              uint2 blockDim [[ threads_per_threadgroup ]])
{
    int w = inTexture.get_width(), h = inTexture.get_height();
    
    threadgroup int shared_memory[THREADGROUP_SIZE];
    threadgroup int shared_memory1[8];
    for(uint j =0; j < h; j += bid.y * (blockDim.y * 2))
    {
        uint i = bid.x * (blockDim.x * 2) + tid.x;//block index * blocksize+thread index
        uint2 pos0  = uint2(i,j), pos1 = uint2(i+blockDim.x);
        shared_memory[tid.x] = inTexture.read(pos0).x + inTexture.read(pos1).x;
        threadgroup_barrier(mem_flags::mem_none);
        // reduction in shared memory
        for (uint s = blockDim.x / 2; s > 0; s >>= 1)
        {
            if (tid.x < s) {
                shared_memory[tid.x] += shared_memory[tid.x + s];
            }
            threadgroup_barrier(mem_flags::mem_none);
        }
        
        // it's not recommended (just to show atomic operation capability)!
        if (0 == tid.x)
        {
            atomic_fetch_add_explicit(shared_memory1[j], shared_memory[0], memory_order_relaxed);
        }
    }
    
    
    //////reduce-y//////
    // reduction in shared memory1
    for (uint s = blockDim / 2; s > 0; s >>= 1)
    {
        if (tid < s) {
            shared_memory1[tid.y] += shared_memory1[tid.y + s];
        }
        threadgroup_barrier(mem_flags::mem_none);
    }
    
    // it's not recommended (just to show atomic operation capability)!
    if (0 == tid.y)
    {
        atomic_fetch_add_explicit(result, shared_memory1[0], memory_order_relaxed);
    }
}
Thanks from ek

**Comment by erickingxu** [comment]
Hi @mateuszbuda ,
I had use params as follows,
And the threadsPerGroup = (16, 16, 1) , numThreadgroup = (8,8,1) for the image size is 512*512, may be a better params for accelerating speed for sum calculation ? 
Thanks from ek

**Comment by mateuszbuda** [comment]
OK, @erickingxu, the most straightforward approach to achieve what you want and allow you to reuse large parts of the code from this example is to reduce each row first and store in the shared memory. Then make a barrier to make sure this array is filled for all rows. If you increase the number of threads in group by adding height dimension in the place where you invoke the kernel, it can be done in the same way as reduction of 1d array. And then you can again reduce the array of sum of rows to obtain the final result. This can be done for each feature channel simultaneously.

**Comment by mdejong** [comment]
Hello. I just published a 2D Prefix Sum implementation for Metal. It might be a useful place to start if you are interested in a 2D texture based implementation. https://github.com/mdejong/MetalPrefixSum
